In [103]:
import torch
import seqm
from seqm.seqm_functions.constants import Constants
from seqm.Molecule import Molecule
from seqm.ElectronicStructure import Electronic_Structure

torch.set_default_dtype(torch.float64)
# if torch.cuda.is_available():
#     device = torch.device('cuda')
# else:
device = torch.device('cpu')
dtype = torch.float64

%load_ext autoreload
%autoreload 2
%reload_ext autoreload
from seqm.seqm_functions.fock import fock
from seqm.seqm_functions.pack import unpack
import seqm.seqm_functions.pack as pack

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [179]:
%%time

### create molecule object:
species = torch.as_tensor([[8,1,1]], # zero-padding for batching
                          dtype=torch.int64, device=device)

coordinates = torch.tensor([
                              [
                               [-0.368758544,      0.000000000,     -1.211413881],
                               [-0.368758544,      0.759337000,     -0.615370881],
                               [-0.368758544,     -0.759337000,     -0.615370881],
                              ]
                            ], device=device)

const = Constants().to(device)

elements = [0]+sorted(set(species.reshape(-1).tolist()))

seqm_parameters = {
                   'method' : 'PM3',  # AM1, MNDO, PM#
                   'scf_eps' : 1.0e-6,  # unit eV, change of electric energy, as nuclear energy doesnt' change during SCF
                   'scf_converger' : [2,0.0], # converger used for scf loop
                                         # [0, 0.1], [0, alpha] constant mixing, P = alpha*P + (1.0-alpha)*Pnew
                                         # [1], adaptive mixing
                                         # [2], adaptive mixing, then pulay
                   'sp2' : [False, 1.0e-5],  # whether to use sp2 algorithm in scf loop,
                                            #[True, eps] or [False], eps for SP2 conve criteria
                   'elements' : elements, #[0,1,6,8],
                   'learned' : [], # learned parameters name list, e.g ['U_ss']
                   #'parameter_file_dir' : '../seqm/params/', # file directory for other required parameters
                   'pair_outer_cutoff' : 1.0e10, # consistent with the unit on coordinates
                   'eig' : True,
                   'excited' : True,
                   }

m = seqm.Molecule.Molecule(const, seqm_parameters, coordinates, species).to(device)

### Create electronic structure driver:
esdriver = Electronic_Structure(seqm_parameters).to(device)

### Run esdriver on m:
esdriver(m)

species tensor([[8, 1, 1]])
species.shape torch.Size([1, 3])
species tensor([[8, 1, 1]])
species.shape torch.Size([1, 3])
tore Parameter containing:
tensor([0., 1., 0., 1., 2., 3., 4., 5., 6., 7., 0., 1., 2., 3., 4., 5., 6., 7., 0.])
qn Parameter containing:
tensor([0., 1., 0., 2., 2., 2., 2., 2., 2., 2., 0., 3., 3., 3., 3., 3., 3., 3., 0.])
nmol 1
molsize 3
P0 torch.Size([1, 12, 12])
tensor([[[1.50000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000],
         [0.00000, 1.50000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000],
         [0.00000, 0.00000, 1.50000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000],
         [0.00000, 0.00000, 0.00000, 1.50000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000],
         [0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000],
         [0.00000

In [334]:
m.C_mo

tensor([[[    -0.87887,     -0.00000,      0.34020,      0.00000,     -0.33445,     -0.00000],
         [    -0.00000,     -0.00000,     -0.00000,      1.00000,     -0.00000,      0.00000],
         [    -0.00000,     -0.77088,     -0.00000,     -0.00000,     -0.00000,      0.63698],
         [    -0.10818,      0.00000,     -0.82490,     -0.00000,     -0.55482,     -0.00000],
         [    -0.32855,     -0.45041,     -0.31921,     -0.00000,      0.53866,     -0.54510],
         [    -0.32855,      0.45041,     -0.31921,     -0.00000,      0.53866,      0.54510]]])

In [515]:
print(m.w.shape)

torch.Size([3, 10, 10])


In [376]:
m.C_mo

tensor([[[    -0.87887,     -0.00000,      0.34020,      0.00000,     -0.33445,     -0.00000],
         [    -0.00000,     -0.00000,     -0.00000,      1.00000,     -0.00000,      0.00000],
         [    -0.00000,     -0.77088,     -0.00000,     -0.00000,     -0.00000,      0.63698],
         [    -0.10818,      0.00000,     -0.82490,     -0.00000,     -0.55482,     -0.00000],
         [    -0.32855,     -0.45041,     -0.31921,     -0.00000,      0.53866,     -0.54510],
         [    -0.32855,      0.45041,     -0.31921,     -0.00000,      0.53866,      0.54510]]])

In [105]:
def decompose_to_sym_antisym(A):
        

    A_sym = 0.5 * (A + A.T)
    A_antisym = 0.5 * (A - A.T)
    
    return A_sym, A_antisym

In [106]:
def ao2mo(M_ao, C):
    """
    transform matrix from AO to MO basis

    Parameters
    ----------
    M_AO : torch tensor # TODO add size
        matrix in AO basis
    C : torch tensor # TODO add size
        matrix of MO coefficients # TODO row or columns, structure?
        
    Returns
    -------
    M_MO : torch tensor # TODO add size
        matrix in MO basis
    """    
    
    M_mo = C.T @ M_ao @ C
    
    return M_MO

In [107]:
def mo2ao(M_mo, molecule, full=False):
    """
    transform matrix from AO to MO basis

    Parameters
    ----------
    M_AO : torch tensor # TODO add size
        matrix in AO basis
    C : torch tensor # TODO add size
        matrix of MO coefficients # TODO row or columns, structure?
        
    Returns
    -------
    M_MO : torch tensor # TODO add size
        matrix in MO basis
    """    
    
    if full == True:
        M_ao = C.T @ M_mo @ C #! does not currently work
        
        return M_ao
    else:
        
        eta = M_mo # TODO rename
        
        eta1 = eta[:N_cis]
        eta1 = eta1.view(-1, m.nvirt[0]) # 1d -> 2d
        print(eta1.shape)
        print('eta1', eta1)
        print('==============')
        
        eta_mo = torch.zeros((m.norb, m.norb), device=device)

        dgemm1 = eta1 @ m.C_mo[0][:, m.nocc:m.norb].T # operations on |X| ?

        # print('dgemm1.shape', dgemm1.shape)
        # print(dgemm1)
        
        eta_mo[:m.nocc] = dgemm1
        # print('eta_mo', eta_mo.shape)
        # print(eta_mo)
        
        
        eta2 = eta[N_cis:]                            # operations on |Y| ?
        eta2 = eta2.view(-1, m.nvirt[0]) # 1d -> 2d
    
        dgemm2 = eta2.T @ m.C_mo[0][:, :m.nocc].T
        
        # print('dgemm2.shape', dgemm2.shape)
        # print(dgemm2)
        
        eta_mo[m.nocc:] = dgemm2
        # print('eta_mo', eta_mo.shape)
        # print(eta_mo)
        
        dgemm3 = m.C_mo[0] @ eta_mo
        eta_ao = dgemm3 
    
    
        return eta_ao

In [108]:
def build_G_ao_sym(M_ao, molecules):
    
      mask     = m.mask, 
      idxi     = m.idxi,
      idxj     = m.idxj,
      w        = m.w,
      nmol = m.nmol
      molsize = m.molsize
      maskd = m.maskd
      idxi = m.idxi
      idxj = m.idxj
      w = m.w
    
    #! works only for H2O
      gss = torch.tensor([15.7558, 14.7942, 14.7942])
      gpp = torch.tensor([13.6540,  0.0000,  0.0000])
      gsp = torch.tensor([10.6212,  0.0000,  0.0000])
      gp2 = torch.tensor([12.4061,  0.0000,  0.0000])
      hsp = torch.tensor([0.5939, 0.0000, 0.0000])
    
    
    
    
      F = torch.zeros((nmol*molsize**2,4,4), device=device) # 0 Fock matrix to fill
      # # TODO: feed params programmatically
      P0 = unpack(M_ao, 1, 2, 12) # 
      P0 = torch.unsqueeze(P0, 0) # add dimension
      
      # print('P0.shape', P0.shape)
      # print('P0\n', P0)
      #---------------fill diagonal 1c-2e -------------------
      P = P0.reshape((nmol,molsize,4,molsize,4)) \
          .transpose(2,3).reshape(nmol*molsize*molsize,4,4)
          
      # print('P.shape', P.shape)
      # print('P\n', P)
      
      Pptot = P[...,1,1]+P[...,2,2]+P[...,3,3]
      ## http://openmopac.net/manual/1c2e.html
    #  (s,s)
      TMP = torch.zeros_like(F)
      TMP[maskd,0,0] = 0.5*P[maskd,0,0]*gss + Pptot[maskd]*(gsp-0.5*hsp)
      for i in range(1,4):
          #(p,p)
          TMP[maskd,i,i] = P[maskd,0,0]*(gsp-0.5*hsp) + 0.5*P[maskd,i,i]*gpp \
                          + (Pptot[maskd] - P[maskd,i,i]) * (1.25*gp2-0.25*gpp)
          #(s,p) = (p,s) upper triangle
          TMP[maskd,0,i] = P[maskd,0,i]*(1.5*hsp - 0.5*gsp)
      #(p,p*)
      for i,j in [(1,2),(1,3),(2,3)]:
          TMP[maskd,i,j] = P[maskd,i,j]* (0.75*gpp - 1.25*gp2)

      F.add_(TMP)
      
           
      #-----------------fill 2c-2e integrals----------------
      weight = torch.tensor([1.0,
                        2.0, 1.0,
                        2.0, 2.0, 1.0,
                        2.0, 2.0, 2.0, 1.0],dtype=dtype, device=device).reshape((-1,10))
      
      PA = (P[maskd[idxi]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,10,1))
      PB = (P[maskd[idxj]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,1,10))
      suma = torch.sum(PA*w,dim=1)
      sumb = torch.sum(PB*w,dim=2)
      sumA = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      sumB = torch.zeros_like(sumA)
      
      sumA[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = suma
      sumB[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = sumb
      F.index_add_(0,maskd[idxi],sumB)
      #\sum_A
      F.index_add_(0,maskd[idxj],sumA)
      
      sum = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      # (ss ), (px s), (px px), (py s), (py px), (py py), (pz s), (pz px), (pz py), (pz pz)
      #   0,     1         2       3       4         5       6      7         8        9

      ind = torch.tensor([[0,1,3,6],
                          [1,2,4,7],
                          [3,4,5,8],
                          [6,7,8,9]],dtype=torch.int64, device=device)
      
      Pp = -0.5*P[mask]
      for i in range(4):
        for j in range(4):
            #\sum_{nu \in A} \sum_{sigma \in B} P_{nu, sigma} * (mu nu, lambda, sigma)
            sum[...,i,j] = torch.sum(Pp*w[...,ind[i],:][...,:,ind[j]],dim=(1,2))
      print('mask', mask[0])    #! DIFFERS FROM PYSEQM, PROBABLY packing
      F.index_add_(0,mask[0],sum)

      F0 = F.reshape(nmol,molsize,molsize,4,4) \
             .transpose(2,3) \
             .reshape(nmol, 4*molsize, 4*molsize)
    #
      F0.add_(F0.triu(1).transpose(1,2))     
      
      F0 = 2 * F0 #! BE CAREFUL
      # print('F0.shape', F0.shape)
      # print(F0) 
      
      return F0

In [109]:
def build_G_ao_antisym(M_ao, molecules):
    
      mask     = m.mask, 
      idxi     = m.idxi,
      idxj     = m.idxj,
      w        = m.w,
      nmol = m.nmol
      molsize = m.molsize
      maskd = m.maskd
      idxi = m.idxi
      idxj = m.idxj
      w = m.w
    
    #! works only for H2O
      gss = torch.tensor([15.7558, 14.7942, 14.7942])  # GSSII   7.87788  7.39710   7.39710   1/2 # not used
      gpp = torch.tensor([13.6540,  0.0000,  0.0000])  # GPPII   6.82700   1/2
      gsp = torch.tensor([10.6212,  0.0000,  0.0000])  # GSPII   10.6211    
      gp2 = torch.tensor([12.4061,  0.0000,  0.0000])  # GP2II   15.5076
      hsp = torch.tensor([0.5939, 0.0000, 0.0000])     # HSPII   0.29694   1/2
   
    
      F = torch.zeros((nmol*molsize**2,4,4), device=device) # 0 Fock matrix to fill
      # # TODO: feed params programmatically
      P0 = unpack(M_ao, 1, 2, 12) # 
      P0 = torch.unsqueeze(P0, 0) # add dimension
      
      # print('P0.shape', P0.shape)
      # print('P0\n', P0)
      #---------------fill diagonal 1c-2e -------------------
      P = P0.reshape((nmol,molsize,4,molsize,4)) \
          .transpose(2,3).reshape(nmol*molsize*molsize,4,4)
          
      # print('P.shape', P.shape)
      # print('P\n', P)
      
      Pptot = P[...,1,1]+P[...,2,2]+P[...,3,3]
      
      
      ## http://openmopac.net/manual/1c2e.html
    #  (s,s)
      TMP = torch.zeros_like(F)
      TMP[maskd,0,0] =  0.5*Pptot[maskd]*(hsp-gsp)
      for i in range(1,4):
          #(p,p)
          TMP[maskd,i,i] = P[maskd,0,0]*(hsp-gsp) + 0.5*P[maskd,i,i]*gpp \
                          + (Pptot[maskd] - P[maskd,i,i]) * (1.25*gp2-0.25*gpp)
          #(s,p) = (p,s) upper triangle
          TMP[maskd,0,i] = P[maskd,0,i]*(hsp-gsp)
      #(p,p*)
      for i,j in [(1,2),(1,3),(2,3)]:
          TMP[maskd,i,j] = P[maskd,i,j]* (0.25*gpp - 0.60*gp2)

      F.add_(TMP)
      
    # ORIGINAL
    #   TMP = torch.zeros_like(F)
    #   TMP[maskd,0,0] = 0.5*P[maskd,0,0]*gss + Pptot[maskd]*(gsp-0.5*hsp)
    #   for i in range(1,4):
    #       #(p,p)
    #       TMP[maskd,i,i] = P[maskd,0,0]*(gsp-0.5*hsp) + 0.5*P[maskd,i,i]*gpp \
    #                       + (Pptot[maskd] - P[maskd,i,i]) * (1.25*gp2-0.25*gpp)
    #       #(s,p) = (p,s) upper triangle
    #       TMP[maskd,0,i] = P[maskd,0,i]*(1.5*hsp - 0.5*gsp)
    #   #(p,p*)
    #   for i,j in [(1,2),(1,3),(2,3)]:
    #       TMP[maskd,i,j] = P[maskd,i,j]* (0.75*gpp - 1.25*gp2)

    #   F.add_(TMP)
      
      
      
           
      #-----------------fill 2c-2e integrals----------------
      weight = torch.tensor([1.0,
                        2.0, 1.0,
                        2.0, 2.0, 1.0,
                        2.0, 2.0, 2.0, 1.0],dtype=dtype, device=device).reshape((-1,10))
      
      PA = (P[maskd[idxi]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,10,1))
      PB = (P[maskd[idxj]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,1,10))
      suma = torch.sum(PA*w,dim=1)
      sumb = torch.sum(PB*w,dim=2)
      sumA = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      sumB = torch.zeros_like(sumA)
      
      sumA[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = suma
      sumB[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = sumb
      F.index_add_(0,maskd[idxi],sumB)
      #\sum_A
      F.index_add_(0,maskd[idxj],sumA)
      
      sum = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      # (ss ), (px s), (px px), (py s), (py px), (py py), (pz s), (pz px), (pz py), (pz pz)
      #   0,     1         2       3       4         5       6      7         8        9

      ind = torch.tensor([[0,1,3,6],
                          [1,2,4,7],
                          [3,4,5,8],
                          [6,7,8,9]],dtype=torch.int64, device=device)
      
      Pp = -0.5*P[mask]
      for i in range(4):
        for j in range(4):
            #\sum_{nu \in A} \sum_{sigma \in B} P_{nu, sigma} * (mu nu, lambda, sigma)
            sum[...,i,j] = torch.sum(Pp*w[...,ind[i],:][...,:,ind[j]],dim=(1,2))
      print('mask', mask[0])    #! DIFFERS FROM PYSEQM, PROBABLY packing
      F.index_add_(0,mask[0],sum)

      F0 = F.reshape(nmol,molsize,molsize,4,4) \
             .transpose(2,3) \
             .reshape(nmol, 4*molsize, 4*molsize)
    #
      F0.add_(F0.triu(1).transpose(1,2))     
      
      F0 = 2 * F0 #! BE CAREFUL
      # print('F0.shape', F0.shape)
      # print(F0) 
      
      return F0

In [287]:
def build_G_2c2e(M_ao, molecules):
    
      mask     = m.mask, 
      idxi     = m.idxi,
      idxj     = m.idxj,
      w        = m.w,
      nmol = m.nmol
      molsize = m.molsize
      maskd = m.maskd
      idxi = m.idxi
      idxj = m.idxj
      w = m.w
    
    #! works only for H2O
      gss = torch.tensor([15.7558, 14.7942, 14.7942])  # GSSII   7.87788  7.39710   7.39710   1/2 # not used
      gpp = torch.tensor([13.6540,  0.0000,  0.0000])  # GPPII   6.82700   1/2
      gsp = torch.tensor([10.6212,  0.0000,  0.0000])  # GSPII   10.6211    
      gp2 = torch.tensor([12.4061,  0.0000,  0.0000])  # GP2II   15.5076
      hsp = torch.tensor([0.5939, 0.0000, 0.0000])     # HSPII   0.29694   1/2
    
    
      F = torch.zeros((nmol*molsize**2,4,4), device=device) # 0 Fock matrix to fill
      # # TODO: feed params programmatically
      P0 = unpack(M_ao, 1, 2, 12) # 
      P0 = torch.unsqueeze(P0, 0) # add dimension
      
      P = P0.reshape((nmol,molsize,4,molsize,4)) \
          .transpose(2,3).reshape(nmol*molsize*molsize,4,4)
          

      #-----------------fill 2c-2e integrals----------------
      weight = torch.tensor([1.0,
                        2.0, 1.0,
                        2.0, 2.0, 1.0,
                        2.0, 2.0, 2.0, 1.0],dtype=dtype, device=device).reshape((-1,10))
      
      PA = (P[maskd[idxi]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,10,1))
      PB = (P[maskd[idxj]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,1,10))
      suma = torch.sum(PA*w,dim=1)
      sumb = torch.sum(PB*w,dim=2)
      sumA = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      sumB = torch.zeros_like(sumA)
      
      sumA[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = suma
      sumB[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = sumb
      F.index_add_(0,maskd[idxi],sumB)
      #\sum_A
      F.index_add_(0,maskd[idxj],sumA)
      
      sum = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      # (ss ), (px s), (px px), (py s), (py px), (py py), (pz s), (pz px), (pz py), (pz pz)
      #   0,     1         2       3       4         5       6      7         8        9

      ind = torch.tensor([[0,1,3,6],
                          [1,2,4,7],
                          [3,4,5,8],
                          [6,7,8,9]],dtype=torch.int64, device=device)
      
      Pp = -0.5*P[mask]
      for i in range(4):
        for j in range(4):
            #\sum_{nu \in A} \sum_{sigma \in B} P_{nu, sigma} * (mu nu, lambda, sigma)
            sum[...,i,j] = torch.sum(Pp*w[...,ind[i],:][...,:,ind[j]],dim=(1,2))
      print('mask', mask[0])    #! DIFFERS FROM PYSEQM, PROBABLY packing
      F.index_add_(0,mask[0],sum)

      F0 = F.reshape(nmol,molsize,molsize,4,4) \
             .transpose(2,3) \
             .reshape(nmol, 4*molsize, 4*molsize)
    #
      F0.add_(F0.triu(1).transpose(1,2))     
      
      #F0 = 2 * F0 #! BE CAREFUL
      # print('F0.shape', F0.shape)
      # print(F0) 
      
      return F0

In [257]:
M2 = mo2ao(vexp1[:m.C_mo.shape[1], :m.C_mo.shape[2]],  m.C_mo[0])

In [110]:
# form quasidiagonal

N_cis = m.nocc * m.nvirt
N_rpa = 2 * m.nocc * m.nvirt
rrwork = torch.zeros(N_rpa * 4, device=device) # rrwork.shape is 64 for H2O
print('rrwork', rrwork)
print('rrwork.shape', rrwork.shape)

#------------- order quaisidiagonal ----------------

i = 0
for ip in range(m.nocc):
    for ih in range(m.nvirt):
        rrwork[i] = m.e_mo[0][m.nocc + ih] - m.e_mo[0][ip]  # !Lancos vectors(i) ???
        i += 1                                                                      #  TODO: [0] should be replaced by m batch index
                                                                                    # ? why 64 if most are 0?
print(rrwork)

rrwork_sorted, indices = torch.sort(rrwork[:N_cis], descending=False)
#---------- end order quaisidiagonal ----------------

# ! rrdpsort 

# ------- Wilkinson shift ---------------------------
#-------end Wilkinson shift -------------------------




rrwork tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
rrwork.shape torch.Size([64])
tensor([40.6148, 41.6759, 21.3483, 22.4095, 18.7318, 19.7929, 16.3584, 17.4196,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000])


In [30]:
torch.set_printoptions(precision=5, linewidth=200, sci_mode=False)

In [54]:
list(m.parameters())

[Parameter containing:
 tensor([0., 1., 0., 1., 2., 3., 4., 5., 6., 7., 0., 1., 2., 3., 4., 5., 6., 7., 0.]),
 Parameter containing:
 tensor([0., 1., 0., 2., 2., 2., 2., 2., 2., 2., 0., 3., 3., 3., 3., 3., 3., 3., 0.]),
 Parameter containing:
 tensor([0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 0, 3, 3, 3, 3, 3, 3, 3, 0]),
 Parameter containing:
 tensor([0., 1., 0., 1., 2., 2., 2., 2., 2., 2., 0., 1., 2., 2., 2., 2., 2., 2., 0.]),
 Parameter containing:
 tensor([0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6., 0., 0., 1., 2., 3., 4., 5., 6.]),
 Parameter containing:
 tensor([0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.]),
 Parameter containing:
 tensor([ 0.,  0.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10.,  0.]),
 Parameter containing:
 tensor([ 0.,  0.,  0.,  0.,  0., -1., -2., -3., -4., -5.,  0.,  0.,  0., -1., -2., -3., -4., -5.,  0.]),
 Parameter containing:
 tensor([ 0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  1.50000,

In [60]:
m.const

Constants()

In [374]:
def davidson_vec():
    
   icount=0
   nd1_old=0
 #  m=0
   n=0
   iloop=0
   itarget = 4
   print('molecules', m)
   # goto 70 - restart
   
   nd  = 10 # dimension of Krylov subspace; usually 5x of excitations to be computed
   
   vexp1 = torch.zeros((N_cis, nd), device=device)
   row_idx = torch.arange(0, int(N_cis), device=device)
   col_idx = indices
   
   vexp1[row_idx, col_idx] = 1.0 
   vexp1[:,itarget:] = 0.0 # return all columns beyond itarget to 0
   
   print('vexp1.shape', vexp1.shape)
   print('vexp1\n', vexp1)
   
   import torch.nn.functional as F
   M = 4  # Size of the desired block
   pad_size = 6  # Number of rows/columns to pad
   
   # vexp1 is X in RPA?

   # vexp = F.pad(vexp1, (0, 0, N_cis, 0))
   
   # vexp = vexp1
   # print('vexp.shape', vexp.shape)
   # print('vexp\n', vexp)
   
   # ORTHONORMALIZATION
   
   
      
   for i in range(4):  # i=nd1_old+1,nd1  
      
      # Lxi testing
      eta = torch.zeros((N_rpa), device=device)
      eta[:vexp1[:,i].shape[0]] = vexp1[:,i] # eta is stored as |X|
      
      # print('eta.shape', eta.shape)
      # print(eta)
      eta_ao =  mo2ao(eta, m.C_mo[0], full=False)     # mo to ao basis (mo2site)
      # TODO  programmatically

      
      # print('eta_ao.shape', eta_ao.shape)
      # print(eta_ao)

      eta_ao_sym, eta_ao_asym = decompose_to_sym_antisym(eta_ao) # decompose to sym and asym
      
      
      # print('reassembled eta ao\n', eta_ao_sym + eta_ao_asym)
      print('eta_ao_asym.shape', eta_ao_asym.shape)
      print(eta_ao_asym)
      
      
      # print('eta_ao_asym.shape', eta_ao_asym.shape)
      # print(eta_ao_asym)
      # Vxi
      
      #------------------symmetric------------------------------
      G_ao_sym   =  build_G_ao_sym(eta_ao_sym, m) 
      # TODO: programmatically feed nHeavy, nHydro
      nHeavy = torch.tensor([1])
      nHydro = torch.tensor([2])
      G_ao_sym = pack.pack(G_ao_sym, nHeavy, nHydro)

      # print('G_ao_sym.shape', G_ao_sym.shape)
      # print('G_ao_sym\n', G_ao_sym)
      
      #------------------end symmetric--------------------------
      
      #-------------------------full---------------------------
     
      # -----------antysim manual------------
      # TODO: adapt build_G for asym part
      l = 0
      
      # make triangular 1d array 
      # print('eta_ao.shape', eta_ao.shape)
      # print(eta_ao)
      eta_anti = torch.zeros((m.norb*(m.norb+1)//2), device=device)
      
      for i in range(m.norb):
          #  print('i', i)
            for j in range(i+1):
              #    print('j', j)
                  
   #               print('l', l)
                  eta_anti[l] = 0.5 * (eta_ao[i,j] - eta_ao[j,i])
                  l += 1
                  
      print('eta_anti.shape', eta_anti.shape)
      print(eta_anti)
      
      eta_anti_2d = torch.zeros((6, 6), device='cpu') 

      # restore to 2d form to build G 2c-2e part
      # l = 0
      # for i in range(0, 6): # TODO" vectorize
      #     for j in range(0,i):
      #         l += 1
      #         eta_anti_2d[i,j] += eta_anti[l-1]
      #         eta_anti_2d[j,i] -= eta_anti[l-1]
      #     l += 1 

      # print('eta_anti_2d.shape', eta_anti_2d.shape)
      # print(eta_anti_2d)
        
      # 2c-2e part of G from antisymmetric guess
      G_ao_antisym_2c2e = build_G_2c2e(eta_ao_asym, m)
      #print('G_ao_antisym_2c2e shape before packing', G_ao_antisym_2c2e.shape)
      G_ao_antisym_2c2e = pack.pack(G_ao_antisym_2c2e, nHeavy, nHydro)
      
      # print('2c-2e antisym\n', G_ao_antisym_2c2e)
      
    #   #--------------fock skew for 1d-array of 1c-2e part of G----------------
      
    #   mask     = m.mask, 
    #   idxi     = m.idxi,
    #   idxj     = m.idxj,
    #   w        = m.w,
    #   nmol = m.nmol
    #   molsize = m.molsize
    #   maskd = m.maskd
    #   idxi = m.idxi
    #   idxj = m.idxj
    #   w = m.w
      
    #   gss = torch.tensor([15.7558, 14.7942, 14.7942])  # GSSII   7.87788  7.39710   7.39710   1/2 # not used
    #   gpp = torch.tensor([13.6540,  0.0000,  0.0000])  # GPPII   6.82700   1/2
    #   gsp = torch.tensor([10.6212,  0.0000,  0.0000])  # GSPII   10.6211    
    #   gp2 = torch.tensor([12.4061,  0.0000,  0.0000])  # GP2II   15.5076
    #   hsp = torch.tensor([0.5939, 0.0000, 0.0000])     # HSPII   0.29694   1/2
      
      
    #   print('maskd', maskd)
    #   F = torch.zeros((nmol*molsize**2,4,4), device=device) # 0 Fock matrix to fill
    #   # # TODO: feed params programmatically
    #   P0 = unpack(eta_ao_asym, 1, 2, 12) # 
    #   P0 = torch.unsqueeze(P0, 0) # add dimension
      
    #   # print('P0.shape', P0.shape)
    #   # print('P0\n', P0)
    #   #---------------fill diagonal 1c-2e -------------------
    #   P = P0.reshape((nmol,molsize,4,molsize,4)) \
    #       .transpose(2,3).reshape(nmol*molsize*molsize,4,4)
          
    #   # print('P.shape', P.shape)
    #   # print('P\n', P)
      
    #   Pptot = P[...,1,1]+P[...,2,2]+P[...,3,3]
      
    #   ## http://openmopac.net/manual/1c2e.html
    # #  (s,s)
    #   TMP = torch.zeros_like(F)
    #   TMP[maskd,0,0] =  0.5*Pptot[maskd]*(hsp-gsp)
    #   for i in range(1,4):
    #       #(p,p)
    #       TMP[maskd,i,i] = P[maskd,0,0]*(hsp-gsp) + 0.0*P[maskd,i,i]*gpp \
    #                       + (Pptot[maskd] - P[maskd,i,i]) * (0.25*gpp - 0.60*15.5076)
    #       #(s,p) = (p,s) upper triangle
    #       TMP[maskd,0,i] = P[maskd,0,i]*(hsp-gsp)
    #   #(p,p*)
    #   for i,j in [(1,2),(1,3),(2,3)]:
    #       TMP[maskd,i,j] = P[maskd,i,j]* (0.25*gpp - 0.60*15.5076) #gp2

    #   F.add_(TMP)

      
    #   F0 = F.reshape(nmol,molsize,molsize,4,4) \
    #          .transpose(2,3) \
    #          .reshape(nmol, 4*molsize, 4*molsize)
    # #
    #   F0.add_(F0.triu(1).transpose(1,2))     
      
    #   F0 = 2 * F0 #! BE CAREFUL
      
    #  # print('F 1c-2e part of antisym', F.shape)
    #   F0 = pack.pack(F0, nHeavy, nHydro)
    #   print('F sym part\n', G_ao_sym)
    #   print('F antisym 2c-2e part\n', G_ao_antisym_2c2e)
    #   print('F 1c-2e part of antisym\n', F0)
    #   print('F total\n',  G_ao_sym + (2*F0 + G_ao_antisym_2c2e))
    # ORIGINAL
    #   TMP = torch.zeros_like(F)
    #   TMP[maskd,0,0] = 0.5*P[maskd,0,0]*gss + Pptot[maskd]*(gsp-0.5*hsp)
    #   for i in range(1,4):
    #       #(p,p)
    #       TMP[maskd,i,i] = P[maskd,0,0]*(gsp-0.5*hsp) + 0.5*P[maskd,i,i]*gpp \
    #                       + (Pptot[maskd] - P[maskd,i,i]) * (1.25*gp2-0.25*gpp)
    #       #(s,p) = (p,s) upper triangle
    #       TMP[maskd,0,i] = P[maskd,0,i]*(1.5*hsp - 0.5*gsp)
    #   #(p,p*)
    #   for i,j in [(1,2),(1,3),(2,3)]:
    #       TMP[maskd,i,j] = P[maskd,i,j]* (0.75*gpp - 1.25*gp2)

    #   F.add_(TMP)
      
      
      pascal2 = [1, 3, 6, 10, 15, 21]  # -1 pascal triangle
      pascal2 = [x -1 for x in pascal2]
      pascal1 = [0, 1, 3, 6, 10, 15] # -1 for python indexing
      pascal1 = [x -1 for x in pascal1]
      orb_loc1 = [0,4,5] # O orbs
      orb_loc2 = [3,4,5]
      F = torch.zeros((m.norb*(m.norb+1)//2))
      # print('F.shape', F.shape)
      # print(F)
      gss = torch.tensor([15.7558, 14.7942, 14.7942])  # GSSII   7.87788  7.39710   7.39710   1/2 # not used
      gpp = torch.tensor([13.6540,  0.0000,  0.0000])  # GPPII   6.82700   1/2
      gsp = torch.tensor([10.6212,  0.0000,  0.0000])  # GSPII   10.6211    
      gp2 = torch.tensor([15.5076,  0.0000,  0.0000])  # GP2II   15.5076   #! take from fortran
      hsp = torch.tensor([0.5939, 0.0000, 0.0000])     # HSPII   0.29694   1/2
      
      print('==============================================')
      for ii in range(3): # n_atoms?
          # print('ii', ii)
          gsp_ii = gsp[ii]
          gpp_ii = gpp[ii]
          gp2_ii = gp2[ii]
          hsp_ii = hsp[ii]
          
          ia = orb_loc1[ii]
          # print('ia', ia)
          ib = orb_loc2[ii]
          
          iplus = ia+1
          ka = pascal2[ia]
          l = ka
          for j in range(iplus, ib+1):
            # print('j', j)
            # print('ia', ia)
            # print('ib', ib)
            # print('l', l)

            mm = l+ia+1
            print('UPPER mm', mm)
            l = l+j+1
            
           # print(type(mm)) 
            F[mm] = F[mm] + 0.5*eta_anti[mm] * (hsp_ii - gsp_ii)
          #  print('(hsp - gsp)', (hsp - gsp))
            print('F[mm]', F[mm])
          iminus = ib-1
          
          for j in range(iplus, iminus+1):
            icc = j
            # print('icc', icc)
            for l in range(icc, ib):
              # print('l', l)
              mm = pascal1[l+1] + j+1
              print('mm', mm)
              print('(0.25*gpp_ii - 0.6*gp2_ii)', (0.25*gpp_ii - 0.6*gp2_ii) )
              F[mm] = F[mm]+ eta_anti[mm] * (0.25*gpp_ii - 0.6*gp2_ii) 
              print('F[mm]', F[mm])
      F = F*2
      print('F antisym\n', F)
      
      # ---------restore asym 1c-2e part to 2d matrix
      G_ao_antisym_1c_2e_1d = F  # as in last lines of build_G
      
      # G_ao_antisym_1c_2e = torch.zeros((6, 6), device='cpu') # for 2d form
      
      G = G_ao_sym[0]
      print('G shape\n', G.shape)
      
      l = 0
      for i in range(0, 6): # TODO" vectorize
          for j in range(0,i):
              l += 1
              # G[i,j] += G_ao_antisym_2c2e[0][i,j]*2 + G_ao_antisym_1c_2e_1d[l-1]
              # G[j,i] -= G_ao_antisym_2c2e[0][j,i]*2 - G_ao_antisym_1c_2e_1d[l-1]
              G[i,j] += G_ao_antisym_1c_2e_1d[l-1]
              G[j,i] -= G_ao_antisym_1c_2e_1d[l-1]             
          l += 1 # skip diagonal
      
      
      
      # l = 0
      # for i in range(0, 6): # TODO" vectorize
      #      for j in range(0,i):
      #          l += 1
      #          G_ao_antisym_1c_2e[i,j] += G_ao_antisym_1c_2e_1d[l-1]
      #          G_ao_antisym_1c_2e[j,i] += G_ao_antisym_1c_2e_1d[l-1]
      #      l += 1 
      #      G_ao_antisym_1c_2e[i,j] += G_ao_antisym_1c_2e_1d[l-1]
          
      print('G 2c-2e antisym\n', G_ao_antisym_2c2e)
      print('G 2c-2e antisym.shape\n', G_ao_antisym_2c2e.shape)
      G_ao_antisym_2c2e =  G_ao_antisym_2c2e[0]
  #     print('G_sym\n', G_ao_sym)
      
  #  #   print('G 1c-2e antisym \n', G_ao_antisym_1c_2e)
      rows, cols = torch.tril_indices(G_ao_antisym_2c2e.shape[0], G_ao_antisym_2c2e.shape[1])

# Multiply the lower triangle elements by -1
      G_ao_antisym_2c2e[rows, cols] *= -1

# Add the diagonal elements back
      G_ao_antisym_2c2e[torch.eye(G_ao_antisym_2c2e.shape[0]).bool()] *= -1


      print('G total \n', G + G_ao_antisym_2c2e*2)
      # -----------end antysim manual------------
      
      
      # for now, 1c-2e would be copied from Vxi_packA line by line
      # print('eta_anti.shape', eta_anti.shape)
      # print(eta_anti)
      # -----------end antysim manual-----------

      # -----------antysim manual------------
      # G_ao = build_G_ao_sym(eta_ao, m)
      # G_ao = pack.pack(G_ao, nHeavy, nHydro)
      # print('========================')
      # print('G_ao.shape', G_ao.shape)
      # print('G_ao\n', G_ao)

            # G_ao_antisym = build_G_ao_antisym(eta_ao_asym, m)
      
      # # print('========================')
      # # print('G_ao_antisym.shape', G_ao_antisym.shape)
      # # print('G_ao_antisym\n', G_ao_antisym)
      
      # print('========================')
      # G_tot = G_ao_sym + G_ao_antisym
      # print('G_tot.shape', G_tot.shape)
      # print('G_tot\n', G_tot)
      
      # TODO: fock1_skew: antisym density is processed differently
      



In [375]:
davidson_vec()

molecules Molecule(
  (const): Constants()
  (parser): Parser()
)
vexp1.shape torch.Size([8, 10])
vexp1
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([4, 2])
eta1 tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]])
eta_ao_asym.shape torch.Size([6, 6])
tensor([[     0.00000,      0.16722,     -0.00000,     -0.00000,      0.00000,      0.00000],
        [    -0.16722,      0.00000,     -0.00000,     -0.27741,      0.26933,      0.26933],
        [     0.00000,      0.00000,      0.00000,      0.00000,     -0.00000,     -0.00000],
        [     0.00000,      0.27741,     -0.00000,      0.00000,     -0.00000,

In [196]:
gsp = torch.tensor([10.6212,  0.0000,  0.0000])

In [200]:
[x for x in range(3)]

[0, 1, 2]

In [205]:
for ii in range(5):
    H[ii] += 1
    print(H[ii])

tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)


In [200]:
H

tensor([1, 2, 3, 4, 5])

In [196]:
H[2](0)

TypeError: 'Tensor' object is not callable

In [175]:
orb_loc = torch.zeros(m.nHeavy + m.nHydro, device=device)

In [172]:
orb_loc

tensor([0., 0., 0.])

In [168]:
# for i in orb_loc:
#     if m.Z[i] != 1:
#         loc = 
#     orb_loc[i] = i if

tensor([0., 0., 0., 0., 0., 0.])

In [153]:
m.Z

tensor([8, 1, 1])

In [113]:
torch.set_printoptions(precision=5, linewidth=200, sci_mode=False)

In [111]:
m.w

tensor([[[10.66662,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [10.20110,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.89358,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [10.69294,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.70142,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
         [ 0.38607,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000,  0.00000],
 

In [112]:
m.w.shape

torch.Size([3, 10, 10])

In [35]:
rrwork[0]

tensor(40.6148)

In [36]:
#-------------Davidson ---------------------

# TODO: restart

# eta
# vexp1.shape = (8, 10) #! CIS guess vector
# vexp                  #! RPA guess vector
# eta is copy of vexp1
# TODO: figure vexp1
# probably orthogonalization could be ommited, if I can print it before and after

# TODO: figure j0

In [28]:
nd  = 10 # dimension of Krylov subspace


In [156]:
vexp1 = torch.zeros((N_cis, nd), device=device)

In [119]:
itarget = 4

In [155]:
row_idx = torch.arange(0, int(N_cis), device=device)
col_idx = indices

In [150]:
row_idx

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [151]:
col_idx

tensor([6, 7, 4, 5])

In [157]:
vexp1[row_idx, col_idx] = 1.0 

In [158]:
vexp1[:,itarget:] = 0.0 # return all columns beyond itarget to 0

In [159]:
vexp1 

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [147]:
f[:, :]

IndexError: too many indices for tensor of dimension 1

In [114]:
vexp1

tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [201]:
ao2mo(m.C_mo[0], m.C_mo[0])

tensor([[-8.7887e-01, -1.2760e-15,  3.4020e-01,  7.2826e-16, -3.3445e-01,
         -1.0343e-15],
        [-3.7279e-16, -8.3358e-16, -6.5134e-16,  1.0000e+00, -1.4109e-16,
          7.8232e-17],
        [-2.9697e-16, -7.7088e-01, -3.4370e-15,  3.3837e-16, -1.2834e-15,
          6.3698e-01],
        [-1.0818e-01,  3.4058e-15, -8.2490e-01, -6.6271e-16, -5.5482e-01,
         -9.5833e-16],
        [-3.2855e-01, -4.5041e-01, -3.1921e-01, -2.0714e-16,  5.3866e-01,
         -5.4510e-01],
        [-3.2855e-01,  4.5041e-01, -3.1921e-01, -4.1659e-16,  5.3866e-01,
          5.4510e-01]])

In [159]:
def davidson():
    
   icount=0
   nd1_old=0
 #  m=0
   n=0
   iloop=0
   itarget = 4
   # goto 70 - restart
   
   nd  = 10 # dimension of Krylov subspace; usually 5x of excitations to be computed
   
   vexp1 = torch.zeros((N_cis, nd), device=device)
   row_idx = torch.arange(0, int(N_cis), device=device)
   col_idx = indices
   
   vexp1[row_idx, col_idx] = 1.0 
   vexp1[:,itarget:] = 0.0 # return all columns beyond itarget to 0
   
   print('vexp1.shape', vexp1.shape)
   print('vexp1\n', vexp1)
   
   import torch.nn.functional as F
   M = 4  # Size of the desired block
   pad_size = 6  # Number of rows/columns to pad
   
   # vexp1 is X in RPA?

   # vexp = F.pad(vexp1, (0, 0, N_cis, 0))
   
   # vexp = vexp1
   # print('vexp.shape', vexp.shape)
   # print('vexp\n', vexp)
   
   # ORTHONORMALIZATION
   
   
   
   # def Lxi(vexp):
      
   #    vexp = ao2mo(vexp, m.C_mo[0]) # vexp to MO basis
      
      
   # def Vxi(vexp):
      
   for i in range(4):  # i=nd1_old+1,nd1  
      
      # Lxi testing
      eta = torch.zeros((N_rpa), device=device)
      eta[:vexp1[:,i].shape[0]] = vexp1[:,i] # eta is stored as |X|
      print(eta)                             #                  |Y|
      
# --------------------------mo2site--------------------------------
      
      # dgemm_x mimics 3 dgemm calls in lioville.F90 NEXMD
      # probably noy efficient in torch

      # print(eta.size())
      # print(eta.shape)
      eta1 = eta[:N_cis]
      eta1 = eta1.view(-1, m.nvirt[0]) # 1d -> 2d
      print(eta1.shape)
      print('eta1', eta1)
      print('==============')
      
      eta_mo = torch.zeros((m.norb, m.norb), device=device)

      dgemm1 = eta1 @ m.C_mo[0][:, m.nocc:m.norb].T # operations on |X| ?

      # print('dgemm1.shape', dgemm1.shape)
      # print(dgemm1)
      
      eta_mo[:m.nocc] = dgemm1
      # print('eta_mo', eta_mo.shape)
      # print(eta_mo)
      
      
      eta2 = eta[N_cis:]                            # operations on |Y| ?
      eta2 = eta2.view(-1, m.nvirt[0]) # 1d -> 2d
   
      dgemm2 = eta2.T @ m.C_mo[0][:, :m.nocc].T
      
      # print('dgemm2.shape', dgemm2.shape)
      # print(dgemm2)
      
      eta_mo[m.nocc:] = dgemm2
      # print('eta_mo', eta_mo.shape)
      # print(eta_mo)
      
      dgemm3 = m.C_mo[0] @ eta_mo
      eta_mo = dgemm3 
      
      # print('dgemm3.shape', dgemm3.shape)
      # print(dgemm3)
      
# --------------------end mo2site--------------------------------
      
#--------------------------- Vxi ---------------------

      xi = eta_mo
      
      # xis size is Nb*(Nb+1)/2; 21 for H2O - store diagonal
      
      # symmertic part
      
      # dest_matrix[range(len(dest_matrix)), range(len(dest_matrix))] = source_vector
      # xi_sym = 0.5 * (xi + xi.T)
      # print('xi_sym.shape', xi_sym.shape)
      
      # xi_asym = 0.5 * (xi - xi.T)
      # print('xi_asym.shape', xi_asym.shape)
      
      #----upper matrix traingle: 21 elements for H2O-----
      
      xis = torch.zeros((m.norb*(m.norb+1)//2), device=device) # TODO: do via sym/antisym matrix decomposition
      l = 0
      for i in range(m.norb):
          #  print('i', i)
            for j in range(i+1):
              #    print('j', j)
                  
   #               print('l', l)
                  xis[l] = 0.5 * (xi[i,j] + xi[j,i])
                  l += 1
                  
      print('xis.shape', xis.shape)
      print('xis\n', xis)
      # -------- triangular -> 2d -------------------  
      
      # tri_idx = torch.triu_indices(int(6), int(6)) # indices of lower traingle [row][col]
      # xis_tri = torch.zeros((6, 6), device=device) 
      # xis_tri[tri_idx[0], tri_idx[1]] = xis # fill lower traingle with xis
      # xis_full = xis_tri + xis_tri.T - torch.diag(torch.diag(xis_tri))
      # print('xis_full\n', xis_full)
      
      xis_full = torch.zeros((6, 6), device='cpu') 

      l = 0
      for i in range(0, 6): # TODO" vectorize
          for j in range(i):
              l += 1
              xis_full[i,j] += xis[l-1]
              xis_full[j,i] += xis[l-1]
          l += 1 
          xis_full[i,i] += xis[l-1]
      
      
      
      # ------------------Vxi pack----------------------
      # xis is not changed in Vxi_pack call
      # eta = fock(nmol     = molecules.nmol[0],
      #            molsize  = molecules.molsize[0],
      #            P0       = xis,
      #            M        = torch.zeros((nmol*molsize**2,4,4))
      #            maskd    = m.maskd,
      mask     = m.mask, 
      idxi     = m.idxi,
      idxj     = m.idxj,
      w        = m.w,
                 

      
      # taken from fock in PYSEQM
      
      nmol = m.nmol
      molsize = m.molsize
      maskd = m.maskd
      idxi = m.idxi
      idxj = m.idxj
      w = m.w
      # TODO extract gxx programmatically
      gss = torch.tensor([15.7558, 14.7942, 14.7942])
      gpp = torch.tensor([13.6540,  0.0000,  0.0000])
      gsp = torch.tensor([10.6212,  0.0000,  0.0000])
      gp2 = torch.tensor([12.4061,  0.0000,  0.0000])
      hsp = torch.tensor([0.5939, 0.0000, 0.0000])

      F = torch.zeros((nmol*molsize**2,4,4), device=device) # 0 Fock matrix to fill
      # # TODO: feed params programmatically
      P0 = unpack(xis_full, 1, 2, 12) # 
      P0 = torch.unsqueeze(P0, 0) # add dimension
      
      print('P0.shape', P0.shape)
      print('P0\n', P0)
      #---------------fill diagonal 1c-2e -------------------
      P = P0.reshape((nmol,molsize,4,molsize,4)) \
          .transpose(2,3).reshape(nmol*molsize*molsize,4,4)
          
      print('P.shape', P.shape)
      print('P\n', P)
      
      Pptot = P[...,1,1]+P[...,2,2]+P[...,3,3]
      ## http://openmopac.net/manual/1c2e.html
    #  (s,s)
      TMP = torch.zeros_like(F)
      TMP[maskd,0,0] = 0.5*P[maskd,0,0]*gss + Pptot[maskd]*(gsp-0.5*hsp)
      for i in range(1,4):
          #(p,p)
          TMP[maskd,i,i] = P[maskd,0,0]*(gsp-0.5*hsp) + 0.5*P[maskd,i,i]*gpp \
                          + (Pptot[maskd] - P[maskd,i,i]) * (1.25*gp2-0.25*gpp)
          #(s,p) = (p,s) upper triangle
          TMP[maskd,0,i] = P[maskd,0,i]*(1.5*hsp - 0.5*gsp)
      #(p,p*)
      for i,j in [(1,2),(1,3),(2,3)]:
          TMP[maskd,i,j] = P[maskd,i,j]* (0.75*gpp - 1.25*gp2)

      F.add_(TMP)
      
           
      #-----------------fill 2c-2e integrals----------------
      weight = torch.tensor([1.0,
                        2.0, 1.0,
                        2.0, 2.0, 1.0,
                        2.0, 2.0, 2.0, 1.0],dtype=dtype, device=device).reshape((-1,10))
      
      PA = (P[maskd[idxi]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,10,1))
      PB = (P[maskd[idxj]][...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)]*weight).reshape((-1,1,10))
      suma = torch.sum(PA*w,dim=1)
      sumb = torch.sum(PB*w,dim=2)
      sumA = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      sumB = torch.zeros_like(sumA)
      
      sumA[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = suma
      sumB[...,(0,0,1,0,1,2,0,1,2,3),(0,1,1,2,2,2,3,3,3,3)] = sumb
      F.index_add_(0,maskd[idxi],sumB)
      #\sum_A
      F.index_add_(0,maskd[idxj],sumA)
      
      sum = torch.zeros(w.shape[0],4,4,dtype=dtype, device=device)
      # (ss ), (px s), (px px), (py s), (py px), (py py), (pz s), (pz px), (pz py), (pz pz)
      #   0,     1         2       3       4         5       6      7         8        9

      ind = torch.tensor([[0,1,3,6],
                          [1,2,4,7],
                          [3,4,5,8],
                          [6,7,8,9]],dtype=torch.int64, device=device)
      
      Pp = -0.5*P[mask]
      for i in range(4):
        for j in range(4):
            #\sum_{nu \in A} \sum_{sigma \in B} P_{nu, sigma} * (mu nu, lambda, sigma)
            sum[...,i,j] = torch.sum(Pp*w[...,ind[i],:][...,:,ind[j]],dim=(1,2))
      print('mask', mask[0])    #! DIFFERS FROM PYSEQM, PROBABLY packing
      F.index_add_(0,mask[0],sum)

      F0 = F.reshape(nmol,molsize,molsize,4,4) \
             .transpose(2,3) \
             .reshape(nmol, 4*molsize, 4*molsize)
    #
      F0.add_(F0.triu(1).transpose(1,2))     
      
      F0 = 2 * F0 #! BE CAREFUL
      print('F0.shape', F0.shape)
      print(F0) 
      break


In [160]:
davidson()

vexp1.shape torch.Size([8, 10])
vexp1
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([4, 2])
eta1 tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]])
xis.shape torch.Size([21])
xis
 tensor([    -0.00000,     -0.16722,     -0.00000,      0.00000,     -0.00000,      0.00000,      0.00000,     -0.27741,      0.00000,      0.00000,      0.00000,      0.26933,     -0.00000,
            -0.00000,     -0.00000,      0.00000,      0.26933,     -0.00000,     -0.00000,     -0.00000,     -0.00000])
P0.shape torch.Size([1, 12, 12])
P0
 tensor([[[