In [2]:
import numpy as np
import torch
import scipy

In [19]:
%load_ext jupyter_ai_magics

In [36]:
%%ai chatgpt
Write a poem about C++.

RateLimitError: You exceeded your current quota, please check your plan and billing details.

In [ ]:
%%ai chatgpt

In [35]:
%env OPENAI_API_KEY=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

env: OPENAI_API_KEY=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


In [28]:
%ai list

| Provider | Environment variable | Set? | Models |
|----------|----------------------|------|--------|
| `ai21` | `AI21_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `ai21:j1-large`, `ai21:j1-grande`, `ai21:j1-jumbo`, `ai21:j1-grande-instruct`, `ai21:j2-large`, `ai21:j2-grande`, `ai21:j2-jumbo`, `ai21:j2-grande-instruct`, `ai21:j2-jumbo-instruct` |
| `bedrock` | Not applicable. | <abbr title="Not applicable">N/A</abbr> | `bedrock:amazon.titan-tg1-large`, `bedrock:anthropic.claude-v1`, `bedrock:anthropic.claude-instant-v1`, `bedrock:ai21.j2-jumbo-instruct`, `bedrock:ai21.j2-grande-instruct` |
| `anthropic` | `ANTHROPIC_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `anthropic:claude-v1`, `anthropic:claude-v1.0`, `anthropic:claude-v1.2`, `anthropic:claude-instant-v1`, `anthropic:claude-instant-v1.0` |
| `cohere` | `COHERE_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `cohere:medium`, `cohere:xlarge` |
| `huggingface_hub` | `HUGGINGFACEHUB_API_TOKEN` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | See https://huggingface.co/models for a list of models. Pass a model's repository ID as the model ID; for example, `huggingface_hub:ExampleOwner/example-model`. |
| `openai` | `OPENAI_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `openai:text-davinci-003`, `openai:text-davinci-002`, `openai:text-curie-001`, `openai:text-babbage-001`, `openai:text-ada-001`, `openai:davinci`, `openai:curie`, `openai:babbage`, `openai:ada` |
| `openai-chat` | `OPENAI_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `openai-chat:gpt-4`, `openai-chat:gpt-4-0314`, `openai-chat:gpt-4-32k`, `openai-chat:gpt-4-32k-0314`, `openai-chat:gpt-3.5-turbo`, `openai-chat:gpt-3.5-turbo-0301` |
| `openai-chat-new` | `OPENAI_API_KEY` | <abbr title="You have not set this environment variable, so you cannot use this provider's models.">❌</abbr> | `openai-chat-new:gpt-4`, `openai-chat-new:gpt-4-0314`, `openai-chat-new:gpt-4-32k`, `openai-chat-new:gpt-4-32k-0314`, `openai-chat-new:gpt-3.5-turbo`, `openai-chat-new:gpt-3.5-turbo-0301` |
| `sagemaker-endpoint` | Not applicable. | <abbr title="Not applicable">N/A</abbr> | Specify an endpoint name as the model ID. In addition, you must include the `--region_name`, `--request_schema`, and the `--response_path` arguments. For more information, see the documentation about [SageMaker endpoints deployment](https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints-deployment.html) and about [using magic commands with SageMaker endpoints](https://jupyter-ai.readthedocs.io/en/latest/users/index.html#using-magic-commands-with-sagemaker-endpoints). |

Aliases and custom commands:

| Name | Target |
|------|--------|
| `gpt2` | `huggingface_hub:gpt2` |
| `gpt3` | `openai:text-davinci-003` |
| `chatgpt` | `openai-chat:gpt-3.5-turbo` |
| `gpt4` | `openai-chat:gpt-4` |


In [8]:
import torch

# Create a random non-symmetric 3x3 matrix
matrix = torch.randn(3, 3)

print(matrix)

ModuleNotFoundError: No module named 'torch'

In [3]:
r_evals, r_vec  = torch.linalg.eig(matrix)

In [6]:
r_evals = r_evals.real

In [7]:
r_vec = r_vec.real

In [17]:
r_vec

tensor([[ 0.2490,  0.9967, -0.8862],
        [ 0.4433,  0.0478, -0.4604],
        [ 0.8611, -0.0663,  0.0523]])

In [18]:
r_evals

tensor([-2.8666,  0.7185,  0.2705])

In [43]:
r_vec @ torch.diag(r_evals) @ torch.inverse(r_vec)

tensor([[ 0.7268, -0.9412, -0.5543],
        [-0.0827,  0.2500, -1.5807],
        [-0.2431,  0.1129, -2.8544]])

###     LEFT EIGENVECTORS

In [ ]:
# TODO: reorder eigenvalues and eigenvectors for left side 

In [20]:
l_evals, l_vec = torch.linalg.eig(matrix.T)

In [21]:
l_evals = l_evals.real
l_vec = l_vec.real

In [35]:
l_vec

tensor([[ 0.4536,  0.0722,  0.0671],
        [-0.8389, -0.8951, -0.0159],
        [ 0.3008,  0.4400,  0.9976]])

In [22]:
l_evals

tensor([ 0.7185,  0.2705, -2.8666])

In [23]:
_, idx = torch.sort(l_evals)

In [24]:
l_evals[idx]

tensor([-2.8666,  0.2705,  0.7185])

In [28]:
mT_rec = l_vec[:, idx] @ torch.diag(l_evals[idx]) @ torch.inverse(l_vec[:, idx])

In [29]:
mT_rec

tensor([[ 0.7268, -0.0827, -0.2431],
        [-0.9412,  0.2500,  0.1129],
        [-0.5543, -1.5807, -2.8544]])

In [30]:
mT_rec.T

tensor([[ 0.7268, -0.9412, -0.5543],
        [-0.0827,  0.2500, -1.5807],
        [-0.2431,  0.1129, -2.8544]])

In [31]:
l_vec[:, idx] @ r_vec

tensor([[ 0.4393,  0.0403, -0.0690],
        [-1.1232, -0.0030,  0.3823],
        [ 0.7024,  0.9954, -1.0709]])

In [33]:
w, vl, vr = scipy.linalg.eig(matrix, left=True)

In [39]:
w

array([-2.8665645 +0.j,  0.71850705+0.j,  0.2704992 +0.j], dtype=complex64)

In [34]:
vl

array([[ 0.06713676,  0.45360634,  0.07221775],
       [-0.01585622, -0.8389088 , -0.89509785],
       [ 0.9976178 ,  0.30078772,  0.43998227]], dtype=float32)

In [38]:
l_vec

tensor([[ 0.4536,  0.0722,  0.0671],
        [-0.8389, -0.8951, -0.0159],
        [ 0.3008,  0.4400,  0.9976]])

In [36]:
vr

array([[ 0.24895024,  0.99665254, -0.8861679 ],
       [ 0.44334868,  0.04781595, -0.46040115],
       [ 0.8610841 , -0.06631196,  0.05231897]], dtype=float32)

In [37]:
r_vec

tensor([[ 0.2490,  0.9967, -0.8862],
        [ 0.4433,  0.0478, -0.4604],
        [ 0.8611, -0.0663,  0.0523]])

In [40]:
l_vec @ matrix @ r_vec

tensor([[-0.5812,  0.3241, -0.1168],
        [ 1.7754, -0.6307,  0.3123],
        [-3.2363,  0.1830, -0.1128]])

In [42]:
l_vec @ r_vec @ torch.diag(r_evals)

tensor([[-0.5812,  0.3241, -0.1168],
        [ 1.7754, -0.6307,  0.3123],
        [-3.2363,  0.1830, -0.1128]])

In [44]:
matrix

tensor([[ 0.7268, -0.9412, -0.5543],
        [-0.0827,  0.2500, -1.5807],
        [-0.2431,  0.1129, -2.8544]])

In [45]:
matrix * torch.tensor([1, 2, 3])

tensor([[ 0.7268, -1.8825, -1.6628],
        [-0.0827,  0.5001, -4.7422],
        [-0.2431,  0.2258, -8.5632]])

In [48]:
atomic_numbers = [8, 1, 1]  # Example atomic numbers for Hydrogen and Oxygen

orb_loc1 = []
orb_loc2 = []

for atomic_number in atomic_numbers:
    if atomic_number == 1:
        orb_loc1.append(0)
        orb_loc2.append(0)
    else:
        orb_loc1.append(orb_loc2[-1] + 1)
        orb_loc2.append(orb_loc2[-1] + 4 - 1)

print("orb_loc1:", orb_loc1)
print("orb_loc2:", orb_loc2)

IndexError: list index out of range

In [51]:
pascal1 = torch.cumsum(torch.arange(0, 6), dim=0) 
pascal1 = pascal1 - 1

In [52]:
pascal1

tensor([-1,  0,  2,  5,  9, 14])

In [114]:
from importlib import reload

In [116]:
# reload module logging
reload(logging)

<module 'logging' from '/scratch/soft/conda/envs/se_exc/lib/python3.10/logging/__init__.py'>

In [23]:
%load_ext autoreload
%autoreload 2

import logging, sys
logging.basicConfig(level=logging.DEBUG,
                    force = True)
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
logFormatter = logging.Formatter(fmt='%(funcName)s :: %(lineno)d :: %(levelname)s :: %(message)s')
# consoleHandler = logging.StreamHandler()
# consoleHandler.setLevel(logging.DEBUG)
# consoleHandler.setFormatter(logFormatter)
# logger.addHandler(consoleHandler)



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [52]:
from colorama import init as colorama_init
from colorama import Fore
from colorama import Style

print(f"This is {Fore.GREEN}color{Style.RESET_ALL}!")

This is color!


In [11]:
from termcolor import colored
print(colored('hello', 'red'), colored('world', 'green'))
print(colored("hello red world", 'red'))

hello world
hello red world


In [23]:
print(colored("hello red world", 'red', 'on_white', attrs=['bold', 'underline']))

hello red world


In [5]:
import logging
logging.basicConfig(level=logging.DEBUG, 
                    format='%(funcName)s :: %(lineno)d :: %(levelname)s :: %(message)s')

QM_LEVEL_NUM = evel=logging.DEBUG - 5
logging.addLevelName(QM_LEVEL_NUM, "FATAL")
def qm(self, message, *args, **kwargs):
    if self.isEnabledFor(QM_LEVEL_NUM):
        self._log(QM_LEVEL_NUM, message, args, **kwargs) 
        
logging.Logger.qm = qm     
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

In [6]:
logger.qm("test")

In [14]:
def format_tensor(tensor):
    return '\n' + str(colored(tensor, 'red'))

In [15]:
logging.info("Hello world %s\n", format_tensor(matrix))

<module> :: 1 :: INFO :: Hello world 
tensor([[ 0.7164, -0.1639, -0.7737],
        [-0.0483, -1.3250,  0.4045],
        [-1.6294, -0.8557, -0.9866]])



In [9]:
matrix = torch.randn(3, 3)

In [99]:

a = 5
b = 0
try:
  c = a / b
except Exception as e:

  logging.exception("Exception occurred")
  
logging.info("Hello world")
logging.debug("Hello world")

ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/tmp/ipykernel_552085/2100013069.py", line 4, in <module>
    c = a / b
ZeroDivisionError: division by zero
INFO:root:Hello world
DEBUG:root:Hello world


In [107]:
logging.debug("Hello world")

DEBUG:root:Hello world


In [108]:
logging.error('%s raised an error', 'name')

ERROR:root:name raised an error


In [109]:
import logging
# Format the log message
logging.basicConfig(format='%(asctime)s %(levelname)s:%(name)s:%(message)s')
# Emit a warning message
logging.warning('You are learning Python logging!')

In [24]:
name = "John"
age = 30

log_message = f"Name: {name!s}, Age: {age!s}"
print(log_message)

Name: John, Age: 30


In [28]:
torch.norm(torch.tensor([    0.18390,      0.47971,     0.11075,     -0.44567,      -0.16180,      -0.70265,     -0.07267]))

tensor(1.0000)

In [30]:
A = torch.tensor([[     0.00019,      0.39385,      0.68065,      0.08393,      0.12593,      0.02553],
        [    -0.00305,     -0.85121,      0.31723,      0.07221,     -0.03733,      0.04126],
        [     0.99588,     -0.00374,      0.00348,     -0.04622,      0.00885,      0.07131],
        [     0.00055,     -0.03038,     -0.09445,     -0.01060,     -0.01580,     -0.01141],
        [    -0.00582,     -0.06560,     -0.07990,     -0.02999,     -0.01007,      0.07922],
        [    -0.01756,      0.06470,      0.00373,     -0.06577,      0.02665,      0.25105],
        [    -0.00898,     -0.12151,      0.12681,     -0.00861,      0.01494,      0.13020],
        [     0.04704,     -0.01807,     -0.15131,      0.61237,      0.50253,     -0.11545],
        [     0.05169,     -0.12784,      0.17780,      0.21873,     -0.04797,     -0.73203],
        [     0.02170,      0.20901,     -0.17349,      0.04403,     -0.02703,     -0.31161],
        [     0.00634,     -0.10987,     -0.55207,     -0.05356,     -0.08935,     -0.11011],
        [     0.01441,      0.11632,      0.00882,      0.04844,     -0.00403,     -0.20311],
        [    -0.00756,     -0.05988,      0.06480,     -0.70860,      0.41245,     -0.32108],
        [     0.04057,      0.07037,      0.10241,     -0.02929,     -0.70903,     -0.24095],
        [     0.01614,     -0.04040,     -0.00739,     -0.17080,      0.21197,     -0.21081],
        [     0.01479,      0.00141,     -0.02137,      0.13435,      0.00750,     -0.03007]])

In [31]:
A = torch.tensor(
       [[     0.00019,      0.39385,      0.68065,      0.08393,      0.12593,      0.02553],
        [    -0.00305,     -0.85121,      0.31723,      0.07221,     -0.03733,      0.04126],
        [     0.99588,     -0.00374,      0.00348,     -0.04622,      0.00885,      0.07131],
        [     0.00055,     -0.03038,     -0.09445,     -0.01060,     -0.01580,     -0.01141],
        [    -0.00582,     -0.06560,     -0.07990,     -0.02999,     -0.01007,      0.07922],
        [    -0.01756,      0.06470,      0.00373,     -0.06577,      0.02665,      0.25105],
        [    -0.00898,     -0.12151,      0.12681,     -0.00861,      0.01494,      0.13020],
        [     0.04704,     -0.01807,     -0.15131,      0.61237,      0.50253,     -0.11545],
        [     0.05169,     -0.12784,      0.17780,      0.21873,     -0.04797,     -0.73203],
        [     0.02170,      0.20901,     -0.17349,      0.04403,     -0.02703,     -0.31161],
        [     0.00634,     -0.10987,     -0.55207,     -0.05356,     -0.08935,     -0.11011],
        [     0.01441,      0.11632,      0.00882,      0.04844,     -0.00403,     -0.20311],
        [    -0.00756,     -0.05988,      0.06480,     -0.70860,      0.41245,     -0.32108],
        [     0.04057,      0.07037,      0.10241,     -0.02929,     -0.70903,     -0.24095],
        [     0.01614,     -0.04040,     -0.00739,     -0.17080,      0.21197,     -0.21081],
        [     0.01479,      0.00141,     -0.02137,      0.13435,      0.00750,     -0.03007]])

In [36]:
A[1, :]

tensor([-0.0030, -0.8512,  0.3172,  0.0722, -0.0373,  0.0413])

In [38]:
torch.norm(A[0, :])

tensor(0.8012)

In [39]:
def orthogonalize_torch(U, eps=1e-15):
    """
    Orthogonalizes the matrix U (d x n) using Gram-Schmidt Orthogonalization.
    If the columns of U are linearly dependent with rank(U) = r, the last n-r columns 
    will be 0.
    
    Args:
        U (numpy.array): A d x n matrix with columns that need to be orthogonalized.
        eps (float): Threshold value below which numbers are regarded as 0 (default=1e-15).
    
    Returns:
        (numpy.array): A d x n orthogonal matrix. If the input matrix U's cols were
            not linearly independent, then the last n-r cols are zeros.
    
    Examples:
    ```python
    >>> import numpy as np
    >>> import gram_schmidt as gs
    >>> gs.orthogonalize(np.array([[10., 3.], [7., 8.]]))
    array([[ 0.81923192, -0.57346234],
       [ 0.57346234,  0.81923192]])
    >>> gs.orthogonalize(np.array([[10., 3., 4., 8.], [7., 8., 6., 1.]]))
    array([[ 0.81923192 -0.57346234  0.          0.        ]
       [ 0.57346234  0.81923192  0.          0.        ]])
    ```
    """
    
    n = len(U[0])
    # numpy can readily reference rows using indices, but referencing full rows is a little
    # dirty. So, work with transpose(U)
    V = U.T
    for i in range(n):
        prev_basis = V[0:i]     # orthonormal basis before V[i]
        coeff_vec = prev_basis @ V[i].T  # each entry is np.dot(V[j], V[i]) for all j < i
        # subtract projections of V[i] onto already determined basis V[0:i]
        V[i] -= (coeff_vec @ prev_basis).T
        if torch.norm(V[i]) < eps:
            V[i][V[i] < eps] = 0.   # set the small entries to 0
        else:
            V[i] /= torch.norm(V[i])
    return V.T

In [40]:
A_orto = orthogonalize_torch(A)

/tmp/ipykernel_587060/3498202963.py:34: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1678411187366/work/aten/src/ATen/native/TensorShape.cpp:3571.)
  coeff_vec = prev_basis @ V[i].T  # each entry is np.dot(V[j], V[i]) for all j < i


In [43]:
A_orto == A

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])

In [44]:
R = torch.tensor([[     0.00487,      9.97446,     16.85499,      1.36908,      1.68907,      0.35934],
        [    -0.07908,    -21.92047,      7.89247,      1.02650,     -0.20035,      0.36962],
        [    25.81744,     -0.08932,      0.06386,     -0.41008,      0.07489,      0.61599],
        [     0.01411,     -0.90634,     -2.49518,     -0.18099,     -0.24790,     -0.17374],
        [    -0.15499,     -0.65752,     -0.82035,     -0.20654,      0.09200,      0.72623],
        [    -0.46512,      0.59608,      0.01199,     -0.62086,      0.14642,      2.40241],
        [    -0.23257,     -1.17181,      1.04003,     -0.33873,      0.12309,      1.10003],
        [     1.21955,     -0.43131,     -2.77491,      5.43359,      4.25084,     -0.99723],
        [     1.33620,     -1.41798,      1.89508,      1.63204,     -0.41887,     -6.21818],
        [     0.56070,      1.69008,     -1.56129,      0.78984,     -0.33191,     -2.73018],
        [     0.16439,     -1.00996,     -4.75088,      0.23844,      0.09762,     -0.72571],
        [     0.37680,      1.12287,      0.05600,      0.51423,     -0.21354,     -1.88172],
        [    -0.19604,     -1.42909,      1.18835,     -6.28742,      3.48889,     -2.77344],
        [     1.05172,      1.67942,      1.87805,     -0.25985,     -5.99765,     -2.08124],
        [     0.41839,     -0.96417,     -0.13556,     -1.51554,      1.79300,     -1.82097],
        [     0.38351,      0.03356,     -0.39200,      1.19205,      0.06348,     -0.25972]])

In [45]:
V = torch.tensor([[     0.00019,      0.39385,      0.68065,      0.08393,      0.12593,      0.02553],
        [    -0.00305,     -0.85121,      0.31723,      0.07221,     -0.03733,      0.04126],
        [     0.99588,     -0.00374,      0.00348,     -0.04622,      0.00885,      0.07131],
        [     0.00055,     -0.03038,     -0.09445,     -0.01060,     -0.01580,     -0.01141],
        [    -0.00582,     -0.06560,     -0.07990,     -0.02999,     -0.01007,      0.07922],
        [    -0.01756,      0.06470,      0.00373,     -0.06577,      0.02665,      0.25105],
        [    -0.00898,     -0.12151,      0.12681,     -0.00861,      0.01494,      0.13020],
        [     0.04704,     -0.01807,     -0.15131,      0.61237,      0.50253,     -0.11545],
        [     0.05169,     -0.12784,      0.17780,      0.21873,     -0.04797,     -0.73203],
        [     0.02170,      0.20901,     -0.17349,      0.04403,     -0.02703,     -0.31161],
        [     0.00634,     -0.10987,     -0.55207,     -0.05356,     -0.08935,     -0.11011],
        [     0.01441,      0.11632,      0.00882,      0.04844,     -0.00403,     -0.20311],
        [    -0.00756,     -0.05988,      0.06480,     -0.70860,      0.41245,     -0.32108],
        [     0.04057,      0.07037,      0.10241,     -0.02929,     -0.70903,     -0.24095],
        [     0.01614,     -0.04040,     -0.00739,     -0.17080,      0.21197,     -0.21081],
        [     0.01479,      0.00141,     -0.02137,      0.13435,      0.00750,     -0.03007]])

In [47]:
V = orthogonalize_torch(V.T)

In [49]:
M = V @ R 

In [50]:
eval, _ = torch.linalg.eig(M)

In [2]:
a = 5


In [6]:
e_mo = torch.tensor([[-36.58831, -17.32189, -14.70534, -12.33198,   4.02645,   5.08758,   0.00000,   0.00000,   0.00000,   0.00000,   0.00000,   0.00000]])

In [15]:
e_mo[0][occ_idx]

tensor([-36.5883, -36.5883, -14.7053, -12.3320])

In [14]:
occ_idx = torch.tensor([0, 0, 2, 3])

In [3]:
# write a function to square number
def square(x):
    return x * x

In [37]:
import numpy as np
import matplotlib.pyplot as plt


def fit_and_plot_best_fit_line(x, y): 
    # Fit a best-fit line using linear regression
    slope, intercept = np.polyfit(x, y, 1)

    # Generate points for the best-fit line
    x_fit = np.linspace(min(x), max(x), 100)
    y_fit = slope * x_fit + intercept

    # Plot the data points and the best-fit line
    plt.scatter(x, y, label='Data')
    plt.plot(x_fit, y_fit, color='red', label='Best Fit Line')

    # Add labels and a legend
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.legend()

    # Show the plot
    plt.show()


In [ ]:
print('Hello World')

In [ ]:
logger

In [ ]:
print(
gjhgj

In [ ]:
TODO

In [62]:
# chech python path from which modules are imported
import sys
sys.path

['/auto/nest/nest/u/fns/github/PYSEQM',
 '/auto/nest/nest/u/fns',
 '/scratch/soft/conda/envs/se_exc/lib/python310.zip',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10/lib-dynload',
 '',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10/site-packages',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10/site-packages/PyQt5_sip-12.11.0-py3.10-linux-x86_64.egg',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10/site-packages/numpy-1.24.2-py3.10-linux-x86_64.egg',
 '/scratch/soft/conda/envs/se_exc/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg']

In [70]:
from test_module import test
import numpy as np

In [71]:
test()

NameError: name 'np' is not defined

In [60]:
# multiply 3d tensors of shape 1, 2, 2
a = torch.tensor([[[1, 2], 
                   [3, 4]]])

b = torch.tensor([[[1, 2], 
                   [3, 4]]])





In [64]:
c = a @ b

In [65]:
c.shape

torch.Size([1, 2, 2])

In [81]:
c.T.shape

torch.Size([2, 2, 1])

In [85]:
c.transpose(1,2).shape

torch.Size([1, 2, 2])

In [63]:
torch.matmul(a, b)

tensor([[[ 7, 10],
         [15, 22]]])

In [105]:
nums1 = [1,2,3,0,0,0]
nums2 = [2,5,6]

In [114]:
def merge(nums1, nums2):
    """
    Do not return anything, modify nums1 in-place instead.
    """
    if len(nums2) != 0:
        nums1[len(nums2):] = nums2
    else:
        pass
    print(nums1)
    #nums1 = [x for x in nums1 if x != 0]
    nums1.sort()
    print(nums1)

    

In [115]:
merge(nums1, nums2)

[1, 2, 3, 2, 5, 6]
[1, 2, 2, 3, 5, 6]


In [116]:
print(nums1)

[1, 2, 2, 3, 5, 6]


In [100]:
def removeElement(nums, val):

    nums = list(filter(lambda x: x != val, nums))
    print(nums)
    return len(nums)

In [101]:
removeElement([3,2,2,3], 3)

[2, 2]


2

In [121]:
a = 121

print(str(a)[::-1])

121


In [151]:
def plusOne( digits):

        num = int("".join([str(x) for x in digits])) + 1
        new_num = list(str(num))
        new_num = [int(x) for x in new_num]
        return new_num

In [154]:
num = plusOne([9,9])
print(num)

[1, 0, 0]


In [17]:
indices = torch.tril_indices(5, 5)
indices.shape

torch.Size([2, 15])

In [18]:
indices

tensor([[0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4],
        [0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4]])

In [6]:
#2 - 3 
#3 - 6
#4 - 10
#5 - 15
#6 - 21
#7 - 28

In [7]:
from math import factorial

In [21]:
def n_triangular_number(number):
    return number * (number + 1) // 2

In [22]:
n_triangular_number(6)

21

In [9]:
A = torch.zeros((1, 21, 21))
B = torch.ones((21, 21))

In [11]:
A.shape

torch.Size([1, 21, 21])

In [12]:
B.shape

torch.Size([21, 21])

In [13]:
A[0] = B

In [15]:
A.shape

torch.Size([1, 21, 21])

In [23]:
A = torch.rand((1, 2, 21))

In [25]:
A

tensor([[[0.0610, 0.4935, 0.2684, 0.0443, 0.0983, 0.8161, 0.2461, 0.4028,
          0.0798, 0.2857, 0.5427, 0.5053, 0.8313, 0.7958, 0.1535, 0.9198,
          0.2401, 0.5798, 0.1565, 0.4939, 0.5032],
         [0.1665, 0.6340, 0.1537, 0.4337, 0.0639, 0.1458, 0.6765, 0.6893,
          0.9654, 0.5101, 0.0032, 0.5954, 0.6509, 0.4628, 0.1142, 0.3407,
          0.1416, 0.4421, 0.5329, 0.3409, 0.1585]]])

In [39]:
A[:, :, 0]

A = torch.rand((2, 8, 6))
B = torch.rand((1, 6, 6))

In [35]:
A @ B

tensor([[[2.7908, 2.5006, 1.5290, 2.2222, 2.1031, 1.9600],
         [2.3464, 2.0375, 1.5260, 1.5997, 1.4620, 1.5213],
         [2.0339, 2.1004, 1.2126, 1.9571, 1.6693, 1.5626],
         [2.1541, 1.9310, 1.1782, 1.4812, 1.7868, 1.4353],
         [2.7768, 2.2477, 1.6642, 1.9844, 1.6790, 2.0041],
         [2.5152, 2.2736, 1.5501, 2.0298, 1.7478, 1.9106],
         [1.9680, 1.9348, 1.2931, 1.7543, 1.4125, 1.4572],
         [1.6052, 1.5016, 1.0296, 1.3513, 1.1270, 1.2185]]])

In [40]:
A

tensor([[[0.7983, 0.7544, 0.3178, 0.8524, 0.6254, 0.2304],
         [0.7409, 0.1969, 0.3356, 0.2516, 0.6514, 0.0749],
         [0.1134, 0.7264, 0.3448, 0.3638, 0.0577, 0.1301],
         [0.1862, 0.5720, 0.0977, 0.6208, 0.2112, 0.1799],
         [0.1440, 0.1869, 0.2486, 0.9734, 0.3681, 0.7415],
         [0.2524, 0.6714, 0.4978, 0.6523, 0.4419, 0.2859],
         [0.8092, 0.0866, 0.7331, 0.9787, 0.9501, 0.3234],
         [0.9634, 0.5732, 0.9926, 0.5362, 0.3210, 0.5119]],

        [[0.3135, 0.5302, 0.0496, 0.7245, 0.5806, 0.8404],
         [0.8174, 0.2210, 0.6348, 0.8099, 0.0050, 0.2634],
         [0.6039, 0.0560, 0.5329, 0.7685, 0.2352, 0.1066],
         [0.1675, 0.6466, 0.6753, 0.3063, 0.1340, 0.7555],
         [0.6916, 0.7769, 0.6700, 0.6257, 0.1588, 0.7063],
         [0.1887, 0.6260, 0.5200, 0.2493, 0.6574, 0.5433],
         [0.9361, 0.0234, 0.5398, 0.0543, 0.0987, 0.2817],
         [0.5155, 0.6970, 0.1319, 0.6312, 0.1158, 0.1322]]])

In [41]:
A[:, :, 0]

tensor([[0.7983, 0.7409, 0.1134, 0.1862, 0.1440, 0.2524, 0.8092, 0.9634],
        [0.3135, 0.8174, 0.6039, 0.1675, 0.6916, 0.1887, 0.9361, 0.5155]])

In [44]:
import torch
import torch.nn.functional as F

# Create a 3D tensor
original_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Specify the desired padding for each dimension
padding_dims = (1, 1, 2, 2, 0, 0)  # (dim0_start, dim0_end, dim1_start, dim1_end, dim2_start, dim2_end)

# Pad the tensor with zeros along specific dimensions
padded_tensor = F.pad(original_tensor, padding_dims, value=0)

print("Original Tensor:")
print(original_tensor)

print("\nPadded Tensor:")
print(padded_tensor)

Original Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Padded Tensor:
tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 1, 2, 0],
         [0, 3, 4, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 5, 6, 0],
         [0, 7, 8, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])
